M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu24.04.1} date 2025-05-29T22:28:56-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-29T22:28:56-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X3.7749Y-4.2612
X3.7749Y-4.4888
M30
